import { cn } from "@/lib/utils";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import { Anek_Telugu } from "next/font/google";
import "./globals.css";

const AnekTelugu = Anek_Telugu({
   subsets: ["latin"],
   variable: "--font-caption",
});

export const metadata: Metadata = {
   title: "Guillaume Zimmer - Full Stack Developer",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" className="h-full">
         <body className={cn(GeistSans.variable, AnekTelugu, "font-sans h-full")}>
            {children}
         </body>
      </html>
   );
}
